openapi: 3.0.0
info:
  title: Authentication API
  version: 1.0.0
paths:
  
  /api/login:
    post:
      summary: User Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password      
                   
                    
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                  token:
                    type: string
        '401':
          description: Unauthorized
        '400':
          description: Bad request
        '500':
          description: Internal server error
